// Class automatically generated by Dev-C++ New Class wizard

#ifndef CLEG_H
#define CLEG_H
#include <wx/string.h>

// An object of this class represents a leg on a course
class CLeg
{
	public:
		// class constructor
		CLeg(long start_CN, long end_CN);
		// class destructor
		~CLeg();
		
		long GetStartCN() {return m_StartCN;};
        long GetEndCN() {return m_EndCN;};
        bool GetUntimed() {return m_Untimed;};
        bool GetOptional() {return m_Optional;};
        bool IsFinishLeg() {return m_EndCN < 0;};
        
        void SetOptional(bool a_Optional) {m_Optional = a_Optional;};
        void SetUntimed(bool a_Untimed) {m_Untimed = a_Untimed;};  
        wxString Label();      
		
    private:
        long m_StartCN;
        long m_EndCN;		
        bool m_Untimed;
        bool m_Optional;
};

#endif // CLEG_H
