// Class automatically generated by Dev-C++ New Class wizard

#ifndef CLEGSTAT_H
#define CLEGSTAT_H
#include <QDateTime>
#include "CPunch.h"

class CResult;

// lightweight class holding statistical information for a single leg for a single runner
class CLegStat
{
	public:
		// class constructor
		CLegStat(CResult* a_Result, int a_Index, CPunch a_Punch);
		// class destructor
		~CLegStat();
		
	   CResult* m_Result;
       long m_Index; // index of leg within course
       long m_ElapsedTime; // elapsed time in seconds
       long m_ElapsedPos;
       long m_ElapsedBehind;

       long m_LegTime;
       long m_LegBehind;
       CPunch m_Punch;  
       long m_LegPos;           
       
};

#endif // CLEGSTAT_H
