// Class automatically generated by Dev-C++ New Class wizard

#ifndef CPUNCH_H
#define CPUNCH_H
#include <QDateTime>
#include <QString>

// Represents a punch at a control
class CPunch
{
	public:
		// class constructor
                CPunch(int a_CN, QString a_DOW, QDateTime a_When);
		CPunch();
		CPunch(const CPunch& a_Copy);
		CPunch& operator=(const CPunch& a_Other);
        bool operator<(const CPunch& a_Other) const;
        bool operator==(const CPunch& a_Other) const;        
        bool operator!=(const CPunch& a_Other) const {return !operator==(a_Other);};         
		
                void SetData(long a_CN, QString a_DOW, QDateTime a_When);
		
		// class destructor
		~CPunch();
		void SetCN(long x); // sets the value of m_CN
		long GetCN(); // returns the value of m_CN
        void SetDOW(QString x); // sets the value of m_DOW
        QString GetDOW(); // returns the value of m_DOW
        void SetWhen(QDateTime x); // sets the value of m_When
        QDateTime GetWhen(); // returns the value of m_When
		void SetIgnore(bool a_Ignore) {m_Ignore = a_Ignore;};
		bool GetIgnore() {return m_Ignore;};		
		
	private:
		// Control Number
		long m_CN;
		// Day of week
                QString m_DOW;
		// Tme that runner punched control
                QDateTime m_When;
		bool m_Ignore;
};

#endif // CPUNCH_H
