// Class automatically generated by Dev-C++ New Class wizard

#include "CSidetails.h" // class's header file

// class constructor
CSiDetails::CSiDetails(long int a_Number): m_Number(a_Number), m_Rental(false)
{
	// insert your code here
}

CSiDetails::CSiDetails(long int a_Number, QString a_Name): m_Number(a_Number), m_Name(a_Name),m_Rental(false)
{
	// insert your code here
}

CSiDetails::CSiDetails(long int a_Number, QString a_Name, QString a_Club): m_Number(a_Number), m_Name(a_Name), m_Club(a_Club),m_Rental(false)
{
	// insert your code here
}		



// class destructor
CSiDetails::~CSiDetails()
{
	// insert your code here
}
		
QString CSiDetails::ExportText()
{
    QString result;
    if (!m_Club.isEmpty())
        {
        result = "%1 %2,%3";
        result.arg(m_Number).arg(m_Name, m_Club);
        }
    else
        {
        result = "%1 %2";
        result.arg(m_Number).arg(m_Name);
        }

    return result;
}
	
