// Class automatically generated by Dev-C++ New Class wizard

#ifndef CSIDETAILS_H
#define CSIDETAILS_H
#include <wx/string.h>

// Objecs in this class represent the known details relating to an SI stick
class CSiDetails
{
	public:
		// class constructor
		CSiDetails(long int a_Number);
		CSiDetails(long int a_Number, wxString a_Name);
		CSiDetails(long int a_Number, wxString a_Name, wxString a_Club);
		
		wxString GetName() {return m_Name;};
		wxString GetClub() {return m_Club;};
		bool GetRental() {return m_Rental;};
		
		wxString SetName(wxString a_Name) {return (m_Name = a_Name);};
		wxString SetClub(wxString a_Club) {return (m_Club = a_Club);};
		bool SetRental(bool a_Rental) {return (m_Rental = a_Rental);};
		
		wxString ExportText();
						
		// class destructor
		~CSiDetails();
		
	private:
		long m_Number;
		wxString m_Name;
		wxString m_Club;
		bool m_Rental;  
};

#endif // CSIDETAILS_H
