// Class automatically generated by Dev-C++ New Class wizard

#include "csidetails.h" // class's header file

// class constructor
CSiDetails::CSiDetails(long int a_Number): m_Number(a_Number), m_Rental(false)
{
	// insert your code here
}

CSiDetails::CSiDetails(long int a_Number, wxString a_Name): m_Number(a_Number), m_Name(a_Name),m_Rental(false)
{
	// insert your code here
}

CSiDetails::CSiDetails(long int a_Number, wxString a_Name, wxString a_Club): m_Number(a_Number), m_Name(a_Name), m_Club(a_Club),m_Rental(false)
{
	// insert your code here
}		



// class destructor
CSiDetails::~CSiDetails()
{
	// insert your code here
}
		
wxString CSiDetails::ExportText()
{
	wxString result;
	if (!m_Club.IsEmpty())
		result.Printf("%ld %s,%s", m_Number, m_Name.c_str(), m_Club.c_str());
	else	
		result.Printf("%ld %s", m_Number, m_Name.c_str());
		
	return result;
}
	
