// Class automatically generated by Dev-C++ New Class wizard

#include "cuniquepunch.h" // class's header file

// class constructor
CUniquePunch::CUniquePunch(CResult* a_Result) : m_Punch(a_Result->GetCheck()), m_SINumber(a_Result->GetSINumber())
{
	// insert your code here
}

// class destructor
CUniquePunch::~CUniquePunch()
{
	// insert your code here
}

bool CUniquePunch::operator<(const CUniquePunch& a_Other) const
{
    if (m_Punch != a_Other.m_Punch)
        return m_Punch < a_Other.m_Punch;
    return m_SINumber < a_Other.m_SINumber;   
}
