// Class automatically generated by Dev-C++ New Class wizard

#ifndef IOBSERVER_H
#define IOBSERVER_H
class ISubject;

// Class describing basic Observer interface
class IObserver
{
	public:

		// class destructor
		virtual ~IObserver(){};
		
		virtual void Update(ISubject* a_ChangedSubject, int a_Hint) = 0;
		
	protected:
		// class constructor
		IObserver(){};
};

#endif // IOBSERVER_H
