// Class automatically generated by Dev-C++ New Class wizard

#ifndef ISUBJECT_H
#define ISUBJECT_H
#include <list>
class IObserver;

// Class describing basic Subject interface
class ISubject
{
	public:

		// class destructor
		virtual ~ISubject();
		
		virtual void Attach(IObserver* a_Observer);
		virtual void Detach(IObserver* a_Observer);
		virtual void Notify(int a_Hint);
		
	protected:
		// class constructor
		ISubject();
	private:
		std::list<IObserver*> m_Observers;
};

#endif // ISUBJECT_H
