// Class automatically generated by Dev-C++ New Class wizard

#include "CLeg.h" // class's header file

// class constructor
CLeg::CLeg(long a_StartCN, long a_EndCN): m_StartCN(a_StartCN), m_EndCN(a_EndCN),
    m_Untimed(false), m_Optional(false)
{
	// insert your code here
}

// class destructor
CLeg::~CLeg()
{
	// insert your code here
}

QString CLeg::Label()
{
    if (m_EndCN < 0)
        return "F";
        
    QString s("%1");
    s.arg(m_EndCN);
    return s;
}
