// Class automatically generated by Dev-C++ New Class wizard

#include "CLegstat.h" // class's header file

// class constructor
CLegStat::CLegStat(CResult* a_Result, int a_Index, CPunch a_Punch): m_Result(a_Result),
m_Index(a_Index), m_ElapsedTime(-1), m_ElapsedPos(-1),
m_ElapsedBehind(-1), m_LegTime(-1), m_Punch(a_Punch), m_LegPos(-1)
{
    // insert your code here
}

// class destructor
CLegStat::~CLegStat()
{
    // insert your code here
}
