// Class automatically generated by Dev-C++ New Class wizard

#ifndef CMESSAGEBOX_H
#define CMESSAGEBOX_H

// No description
class CMessageBox
{
	public:
		// class constructor
		CMessageBox(const wxString& a_Message, const wxString& a_Caption, long a_Style);
		// class destructor
		~CMessageBox();
};

#endif // CMESSAGEBOX_H
