// Class automatically generated by Dev-C++ New Class wizard

#include "cmessagebox.h" // class's header file

// class constructor
CMessageBox::CMessageBox(const wxString& a_Message, const wxString& a_Caption, long a_Style)
{
	// insert your code here
}

// class destructor
CMessageBox::~CMessageBox()
{
	// insert your code here
}
