// Class automatically generated by Dev-C++ New Class wizard

#include "cpunch.h" // class's header file
#include "Utils.h"

// class constructor
CPunch::CPunch(int a_CN, wxString a_DOW, wxDateTime a_When) : m_CN(a_CN), m_DOW(a_DOW), m_When(a_When),m_Ignore(false)
{
	// insert your code here
}

CPunch::CPunch(const CPunch& a_Copy) : m_CN(a_Copy.m_CN), m_DOW(a_Copy.m_DOW), m_When(a_Copy.m_When),m_Ignore(false)
{
}

CPunch::CPunch()
{
}

CPunch& CPunch::operator=(const CPunch& a_Other)
{
    m_CN = a_Other.m_CN;
    m_DOW = a_Other.m_DOW;
    m_When = a_Other.m_When;
    return *this;
}

bool CPunch::operator<(const CPunch& a_Other) const
{
    if (m_CN != a_Other.m_CN)
        return m_CN < a_Other.m_CN;
    if (m_DOW != a_Other.m_DOW)
        return DOWToInt(m_DOW) < DOWToInt(a_Other.m_DOW);
          
    return m_When.IsEarlierThan(a_Other.m_When);   
}

bool CPunch::operator==(const CPunch& a_Other) const
{
    return m_CN == a_Other.m_CN && m_DOW == a_Other.m_DOW && m_When.IsEqualTo(a_Other.m_When);
}

void CPunch::SetData(long a_CN, wxString a_DOW, wxDateTime a_When)
{
    m_CN = a_CN;
    m_DOW = a_DOW;
    m_When = a_When;
}

// class destructor
CPunch::~CPunch()
{
	// insert your code here
}


// returns the value of m_CN
long CPunch::GetCN()
{
	return m_CN;
}


// sets the value of m_CN
void CPunch::SetCN(long x)
{
	m_CN = x;
}


// returns the value of m_DOW
wxString CPunch::GetDOW()
{
	return m_DOW;
}


// sets the value of m_DOW
void CPunch::SetDOW(wxString x)
{
	m_DOW = x;
}


// returns the value of m_When
wxDateTime CPunch::GetWhen()
{
	return m_When;
}


// sets the value of m_When
void CPunch::SetWhen(wxDateTime x)
{
	m_When = x;
}
