// Class automatically generated by Dev-C++ New Class wizard

#ifndef CUNIQUEPUNCH_H
#define CUNIQUEPUNCH_H
#include "CResult.h"

// Combination of a CPunch and an SI number. USed for unique sort when detecting duplicates
class CUniquePunch
{
	public:
		// class constructor
		CUniquePunch(CResult* a_Result);
		// class destructor
		~CUniquePunch();
        bool operator<(const CUniquePunch& a_Other) const;		
		
		// Default copy constructor is OK
		
        CPunch m_Punch;
        long m_SINumber;		
};

#endif // CUNIQUEPUNCH_H
