// Class automatically generated by Dev-C++ New Class wizard

#ifndef CXMLWRITER_H
#define CXMLWRITER_H
#include <wx/string.h>
#include <stack>

// Objects in this class can be used to create then write out an XML tree
class CXmlWriter
{
	public:
		// class constructor
		CXmlWriter(wxString a_DocType, wxString a_DtdName);
		// class destructor
		~CXmlWriter();
		void StartElement(wxString a_ElementName, wxString a_Attributes = wxEmptyString);
		void EndElement();
		void AddValue(wxString a_Value);
		bool WriteToFile(wxString a_File);
		
    private:
        wxString m_Output;
        std::stack<wxString> m_Elements;
        bool m_GotValue;
        wxString m_LastElement;				
};

#endif // CXMLWRITER_H
